Repository pagopa/pagopa-afm-utils, pull requests merged in 2022-09, with the labels that each got.

#2 Added PSP as Touchpoint value
  openapi/openapi.json
  src/main/java/it/gov/pagopa/afm/calculator/model/Touchpoint.java
  src/main/java/it/gov/pagopa/afm/calculator/service/ConfigurationService.java
Labels: bug

#4 CD Pipeline
  .devops/deploy-pipelines.yml
  .github/workflows/anchore.yml
  .github/workflows/deploy.yml
  .github/workflows/update_infra.yml
  Dockerfile
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: bug

#6 feat: [PGEC-65] Async data workflow
  api-test/AFM - Azure Dev.postman_environment.json
  api-test/AFM Calculator Data.postman_collection.json
  api-test/AFM Calculator.postman_collection.json
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/afm/calculator/Application.java
  src/main/java/it/gov/pagopa/afm/calculator/config/FeignConfig.java
  src/main/java/it/gov/pagopa/afm/calculator/config/SchedulerConfig.java
  src/main/java/it/gov/pagopa/afm/calculator/controller/BaseController.java
  src/main/java/it/gov/pagopa/afm/calculator/controller/ConfigurationController.java
  src/main/java/it/gov/pagopa/afm/calculator/entity/CiBundleAttribute.java
  src/main/java/it/gov/pagopa/afm/calculator/model/configuration/Configuration.java
  src/main/java/it/gov/pagopa/afm/calculator/service/ConfigurationService.java
  src/main/java/it/gov/pagopa/afm/calculator/service/MarketPlaceClient.java
  src/main/java/it/gov/pagopa/afm/calculator/task/ConfigurationTask.java
  src/main/java/it/gov/pagopa/afm/calculator/task/MarketPlaceTrigger.java
  src/main/java/it/gov/pagopa/afm/calculator/task/SchedulerTask.java
  src/main/java/it/gov/pagopa/afm/calculator/util/AzuriteStorageUtil.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: enhancement

#7 fix azurite
  src/main/java/it/gov/pagopa/afm/calculator/task/ConfigurationTask.java
Labels: bug

#8 Helm Values
  helm/values-prod.yaml
Labels: ignore-for-release
