Repository pagopa/pagopa-afm-utils, pull requests merged in 2023-02, with the labels that each got.

#15 [PAGOPA-633] add abi to CDI: added abi and updated junit test
  src/main/java/it/gov/pagopa/afm/utils/entity/CDI.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/BundleRequest.java
  src/main/java/it/gov/pagopa/afm/utils/service/CDIService.java
  src/test/resources/cdi/cdi.json
  src/test/resources/cdi/cdi_PO.json
  src/test/resources/cdi/cdi_service_amount.json
  src/test/resources/cdi/cdi_status_FAILED.json
  src/test/resources/cdi/cdi_wisp_io_checkout.json
Labels: bug

#16 GitHub action
  .github/workflows/anchore.yml
  .github/workflows/assignee.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy.yml
  .github/workflows/deploy_aks.yml
  .github/workflows/sonar_analysis.yml
  .github/workflows/update_code.yml
  .gitignore
  utilities/cosmos.sh
Labels: size/large

#17 fix
  .editorconfig
  .github/workflows/check_pr.yml
  .github/workflows/update_code.yml
  .gitignore
  .pre-commit-config.yaml
  intellij-java-google-style.xml
  openapi/generate_openapi.sh
  pom.xml
  src/main/java/it/gov/pagopa/afm/utils/Application.java
Labels: ignore-for-release, size/large

#18 fix
  .github/workflows/update_code.yml
  .github/workflows/update_infra.yml
  docker/config/.env
  docker/config/marketplace.env
  docker/docker-compose.yml
  docker/run_docker.sh
  openapi/openapi.json
  src/main/resources/application.properties
Labels: ignore-for-release, size/large

#19 fix
  .github/workflows/check_pr.yml
  .github/workflows/update_code.yml
  .github/workflows/update_infra.yml
Labels: size/small

#20 PAT
  .github/workflows/deploy_aks.yml
  .github/workflows/update_code.yml
  docker/run_docker.sh
Labels: ignore-for-release, size/small

#21 trigger
  .github/workflows/update_code.yml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/afm/utils/Constants.java
  src/main/java/it/gov/pagopa/afm/utils/ImportCDIFunction.java
  src/main/java/it/gov/pagopa/afm/utils/ImportCDIHandler.java
  src/main/java/it/gov/pagopa/afm/utils/config/CosmosDBConfiguration.java
  src/main/java/it/gov/pagopa/afm/utils/config/FeignConfig.java
  src/main/java/it/gov/pagopa/afm/utils/config/LoggingAspect.java
  src/main/java/it/gov/pagopa/afm/utils/config/MappingsConfiguration.java
  src/main/java/it/gov/pagopa/afm/utils/config/OpenApiConfig.java
  src/main/java/it/gov/pagopa/afm/utils/config/RequestFilter.java
  src/main/java/it/gov/pagopa/afm/utils/config/SchedulerConfig.java
  src/main/java/it/gov/pagopa/afm/utils/controller/BaseController.java
  src/main/java/it/gov/pagopa/afm/utils/controller/ImportCDIController.java
  src/main/java/it/gov/pagopa/afm/utils/entity/CDI.java
  src/main/java/it/gov/pagopa/afm/utils/entity/Detail.java
  src/main/java/it/gov/pagopa/afm/utils/entity/ServiceAmount.java
  src/main/java/it/gov/pagopa/afm/utils/entity/StatusType.java
  src/main/java/it/gov/pagopa/afm/utils/exception/AppError.java
  src/main/java/it/gov/pagopa/afm/utils/exception/AppException.java
  src/main/java/it/gov/pagopa/afm/utils/exception/ErrorHandler.java
  src/main/java/it/gov/pagopa/afm/utils/model/AppInfo.java
  src/main/java/it/gov/pagopa/afm/utils/model/ProblemJson.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/BundleRequest.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/BundleResponse.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/BundleType.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/CDIWrapper.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/PaymentMethodType.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/TouchpointType.java
  src/main/java/it/gov/pagopa/afm/utils/repository/CDICollectionRepository.java
  src/main/java/it/gov/pagopa/afm/utils/service/CDIService.java
  src/main/java/it/gov/pagopa/afm/utils/service/MarketPlaceClient.java
  src/main/java/it/gov/pagopa/afm/utils/task/MarketPlaceTrigger.java
  src/main/java/it/gov/pagopa/afm/utils/task/SchedulerTask.java
  src/test/java/it/gov/pagopa/afm/utils/ApplicationTest.java
  src/test/java/it/gov/pagopa/afm/utils/ImportCDIFunctionTest.java
  src/test/java/it/gov/pagopa/afm/utils/ImportCDIHandlerTest.java
  src/test/java/it/gov/pagopa/afm/utils/common/TestUtil.java
  src/test/java/it/gov/pagopa/afm/utils/config/MockConfiguration.java
  src/test/java/it/gov/pagopa/afm/utils/controller/ImportCDIControllerTest.java
  src/test/java/it/gov/pagopa/afm/utils/service/CDIServiceTest.java
Labels: ignore-for-release, size/large
