Repository pagopa/pagopa-afm-utils, pull requests merged in 2023-01, with the labels that each got.

#10 [PAGOPA-360] import cdi
  .devops/code-review-pipelines.yml
  .github/workflows/deploy.yml
  .github/workflows/sonar_analysis.yml
  .github/workflows/update_infra.yml
  Dockerfile
  docker/docker-compose.yml
  openapi/openapi.json
  pom.xml
  src/main/azure/host.json
  src/main/azure/local.settings.json
  src/main/java/it/gov/pagopa/afm/utils/Application.java
  src/main/java/it/gov/pagopa/afm/utils/ImportCDIFunction.java
  src/main/java/it/gov/pagopa/afm/utils/ImportCDIHandler.java
  src/main/java/it/gov/pagopa/afm/utils/config/CosmosDBConfiguration.java
  src/main/java/it/gov/pagopa/afm/utils/entity/CDI.java
  src/main/java/it/gov/pagopa/afm/utils/entity/Detail.java
  src/main/java/it/gov/pagopa/afm/utils/entity/ServiceAmount.java
  src/main/java/it/gov/pagopa/afm/utils/entity/StatusType.java
  src/main/java/it/gov/pagopa/afm/utils/exception/AppError.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/BundleRequest.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/BundleResponse.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/BundleType.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/CDIWrapper.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/PaymentMethodType.java
  src/main/java/it/gov/pagopa/afm/utils/model/bundle/TouchpointType.java
  src/main/java/it/gov/pagopa/afm/utils/repository/CDICollectionRepository.java
  src/main/java/it/gov/pagopa/afm/utils/service/CDIService.java
  src/main/java/it/gov/pagopa/afm/utils/service/MarketPlaceClient.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/afm/utils/ImportCDIFunctionTest.java
  src/test/java/it/gov/pagopa/afm/utils/ImportCDIHandlerTest.java
  src/test/java/it/gov/pagopa/afm/utils/common/TestUtil.java
  src/test/java/it/gov/pagopa/afm/utils/config/MockConfiguration.java
  src/test/java/it/gov/pagopa/afm/utils/service/CDIServiceTest.java
  src/test/resources/application.properties
  src/test/resources/cdi/cdi.json
  src/test/resources/cdi/cdi_PO.json
  src/test/resources/cdi/cdi_service_amount.json
  src/test/resources/cdi/cdi_status_FAILED.json
  src/test/resources/cdi/cdi_wisp_io_checkout.json
Labels: enhancement

#11 feat: Fix port
  Dockerfile
Labels: ignore-for-release

#12 added affinity
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: ignore-for-release

#13 [PAGOPA-627] get call: refactoring from httpTrigger to spring rest call
  Dockerfile
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/afm/utils/ImportCDIFunction.java
  src/main/java/it/gov/pagopa/afm/utils/config/FeignConfig.java
  src/main/java/it/gov/pagopa/afm/utils/controller/ImportCDIController.java
  src/main/java/it/gov/pagopa/afm/utils/exception/AppException.java
  src/main/java/it/gov/pagopa/afm/utils/repository/CDICollectionRepository.java
  src/main/java/it/gov/pagopa/afm/utils/service/CDIService.java
  src/main/java/it/gov/pagopa/afm/utils/task/MarketPlaceTrigger.java
  src/test/java/it/gov/pagopa/afm/utils/ImportCDIFunctionTest.java
  src/test/java/it/gov/pagopa/afm/utils/ImportCDIHandlerTest.java
  src/test/java/it/gov/pagopa/afm/utils/controller/ImportCDIControllerTest.java
  src/test/java/it/gov/pagopa/afm/utils/service/CDIServiceTest.java
Labels: bug, enhancement

#14 Fix Helm Values
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/afm/utils/Constants.java
  src/main/java/it/gov/pagopa/afm/utils/config/FeignConfig.java
  src/main/java/it/gov/pagopa/afm/utils/config/OpenApiConfig.java
  src/main/java/it/gov/pagopa/afm/utils/config/RequestFilter.java
Labels: bug
